server:
  port: 8080
spring:
  application:
    name: nacos-demo
  cloud:
    nacos:
      discovery:
        server-addr: 121.199.163.188:8848
        username: nacos
        password: nacos
        namespace: wk
mybatis:
  mapper-locations: classpath:mappers/*xml
  type-aliases-package: com.wangkun.pojo